jwtauth:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28880

spring:
  profiles:
    active: local
  output:
    ansi:
      enabled: always
server:
  port: 8082

---
spring:
  profiles: local
  data:
    mongodb:
      database: seshstorage
      host: ds233323.mlab.com
      port: 33323
      username: admin
      password: admin22

jwtauth:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave512bitsKeySize
    expiration: 28880

---
spring:
  profiles: dev
  data:
    mongodb:
      database: seshstorage
      host: ds233323.mlab.com
      port: 33323
      username: admin
      password: admin22

---
spring:
  profiles: test
  data:
    mongodb:
      port: 0
